version: '3.8'

services:
  postgres:
    image: postgres:15.3-alpine3.18
    restart: always
    container_name: database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - postgres-network
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d production"]
      interval: 30s
      timeout: 10s
      retries: 5
    cpus: '2'  # Limit to 2 CPU cores
    mem_limit: '2g'  # Limit to 2 GB of RAM

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres-data:
