version: '3.8'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_DEFAULT_VHOST: vhost
    networks:
      - properties_network
    healthcheck:
      test: ["CMD", "rabbitmqctl", "list_users"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

  redis:
    container_name: cache
    image: redis:alpine3.18
    restart: always
    ports:
      - 6379:6379
    networks:
      - properties_network

networks:
  properties_network:
    external: false
